# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
